---
app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: http://localhost:7007

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: http://localhost:7007
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  auth:
    keys:
      - secret: ${BACKSTAGE_AUTH_KEYS_0}

  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  locations:
    # Backstage entities
    - type: file
      target: /app/entities.yaml

    # Resource Provisioner template
    - type: file
      target: /app/resource-provisioner.yaml

      rules:
        - allow: [Template]

    # GCP Project Provisioner template
    - type: file
      target: /app/gcp-project-provisioner.yaml

      rules:
        - allow: [Template]

    # Backstage organizational data
    - type: file
      target: /app/org.yaml
      rules:
        - allow: [User, Group]

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'gke'
      projectId: ${GCP_PROJECT_ID}
      region: ${GCP_PROJECT_REGION}
      skipTLSVerify: true
      skipMetricsLookup: true
      exposeDashboard: true

auth:
  environment: production
  providers:
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}

  # We configure a custom sign-in resolver until we can manage Users and Groups with Secure LDAP.
  # See https://backstage.io/docs/auth/identity-resolver#sign-in-without-users-in-the-catalog
  allowedDomains: ${AUTH_GOOGLE_ALLOWED_DOMAINS}
