---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: data-science-portal
  title: Data Science Portal
spec:
  owner: group:platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: Backstage
  description: Backstage Application
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: group:platform-team
  lifecycle: experimental
