---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates-google
  title: Templates - Google
spec:
  type: file
  targets:
    - ./project-create/template.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates-rad-lab
  title: Templates - Rad Lab Modules
spec:
  type: file
  targets:
    - ./rad-lab-data-science-create/template.yaml
    - ./rad-lab-gen-ai-create/template.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates-backstage
  title: Templates - Backstage
spec:
  type: file
  targets:
    - ./add-user/template.yaml
