---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: data-science-portal
  title: Data Science Portal
spec:
  owner: group:platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  title: Platform Team
spec:
  type: root
  children: []
