---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-create
  title: Project Template
  description: Create a GCP Project with a budget and budget alerts. The Platform Team will review your request before the Project is created.
spec:
  owner: platform-team
  type: project
  parameters:
    - title: Project
      required:
        - department
        - dataClassification
        - vanityName
      properties:
        department:
          title: Department
          description: The department ID.
          type: string
          default: ph
          enum:
            - ph
            - hc
          enumNames:
            - PHAC
            - Health Canada
        dataClassification:
          title: Data Classification
          description: The level of security for the project information and assets.
          type: string
          default: UCLL
          enum:
            - UCLL
            - PBMM
          enumNames:
            - Unclassified
            - Protected B
        vanityName:
          title: Vanity Name
          description: The resource display name. The name must less than 26 characters. The name will be used to create a GCP Project named `<department>-<vanity-name>` in [HC-DMIA > DMIA-PHAC > SciencePlatform](https://console.cloud.google.com/cloud-resource-manager?folder=108494461414).
          type: string
          maxLength: 26
    - title: Administration
      required:
        - costCentre
        - section32ManagerEmail
        - justification
      properties:
        costCentre:
          title: Cost Centre
          type: string
        costCentreName:
          title: Cost Centre Name
          description: The human-readable name for the Cost Centre.
          type: string
        section32ManagerEmail:
          title: Section 32 Manager Email Address
          type: string
          format: email
        justification:
          title: Justification
          ui:description: Provide a brief explanation of what the project will be used for.
          type: string
          ui:widget: textarea
          ui:options:
            rows: 2
        owners:
          title: Owners
          ui:description: The `@gcp.hc-sc.gc.ca` email addresses of users who should own this service, separated by comma.
          type: string
          ui:widget: textarea
          ui:options:
            rows: 2
          ui:placeholder: jane.doe@gcp.hc-sc.gc.ca, john.doe@gcp.hc-sc.gc.ca, steve.smith@gcp.hc-sc.gc.ca
        editors:
          title: Editors
          ui:description: The `@gcp.hc-sc.gc.ca` email addresses of users who should be able to edit this service, separated by comma.
          type: string
          ui:widget: textarea
          ui:options:
            rows: 2
          ui:placeholder: jane.doe@gcp.hc-sc.gc.ca, john.doe@gcp.hc-sc.gc.ca, steve.smith@gcp.hc-sc.gc.ca
    - title: Billing
      required:
        - budgetAmount
      properties:
        budgetAmount:
          title: Annual Budget Amount (CAD)
          type: number
          default: 2000
        budgetAlertEmailRecipients:
          title: Budget Alert Email Recipients
          ui:description: The `@phac-aspc.gc.ca` email addresses of users who should be notified of budget alerts, separated by a comma.
          type: string
          ui:widget: textarea
          ui:options:
            rows: 2
          ui:placeholder: jane.doe@phac-aspc.gc.ca, john.doe@phac-aspc.gc.ca, steve.smith@phac-aspc.gc.ca
    - title: Pull Request
      backstage:featureFlag: template-developer
      properties:
        pullRequestAction:
          title: Pull Request Action
          type: string
          default: Diff Only
          enum:
            - Diff Only
            - Publish and Close Pull Request
            - Publish Pull Request

  steps:
    - id: ctx
      name: Get Context
      action: data-science-portal:template:get-context
      input:
        # Pass the parameters as an input to include all user inputs.
        parameters: ${{parameters}}

    - id: prepare-pull-request
      name: Prepare Pull Request
      action: fetch:template
      input:
        url: ./${{steps.ctx.output.template}}/changes
        values: ${{steps.ctx.output.template_values}}

    - id: debug-pull-request
      name: Debug Pull Request
      action: debug:workspace
      if: ${{ parameters.pullRequestAction == 'Diff Only' }}
      backstage:featureFlag: template-developer
      input:
        command: diff
        workingDirectory: . # the workspacePath
        args: ${{ parameters.args }}

    - id: publish-pull-request
      name: Submit Pull Request
      action: publish:github:pull-request
      if: ${{ parameters.pullRequestAction != 'Diff Only' }}
      input:
        repoUrl: github.com?owner=${{steps.ctx.output.repo_owner}}&repo=${{steps.ctx.output.repo_name}}
        branchName: ${{steps.ctx.output.branch}}
        title: ${{steps.ctx.output.pr_title}}
        description: ${{steps.ctx.output.pr_description}}
        targetPath: ./DMIA-PHAC/SciencePlatform/${{steps.ctx.output.template_values.projectName}}

  output:
    links:
      - url: ${{steps.publish-pull-request.output.remoteUrl}}
        title: 'View Pull Request'
