---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-create
  title: Project Template
  description: Create a GCP Project with a budget and budget alerts.
spec:
  owner: platform-team
  type: project
  parameters:
    - title: Project
      required:
        - department
        - environment
        - vanityName
      properties:
        department:
          title: Department
          type: string
          default: ph
          enum:
            - ph
            - hc
          enumNames:
            - PHAC
            - Health Canada
        environment:
          title: Environment
          type: string
          default: x
          enum:
            - x
            - t
            - p
          enumNames:
            - Experimentation
            - Testing
            - Production
        vanityName:
          title: Vanity Name
          type: string
          description: The resource display name. The name must less than 27 characters. The name will be used to create a GCP Folder named `<department>-<vanity-name>` and Project named `<department><environment>-<vanity-name>` in [HC-DMIA > DMIA-PHAC > SciencePlatform](https://console.cloud.google.com/cloud-resource-manager?folder=108494461414).
          default:
          maxLength: 27
    - title: Administration
      required:
        - costCentre
        - section32ManagerEmail
        - justification
      properties:
        costCentre:
          title: Cost Centre
          type: string
        section32ManagerEmail:
          title: Section 32 Manager Email Address
          type: string
          format: email
        justification:
          title: Justification
          type: string
          ui:widget: textarea
          ui:description: Provide a brief explanation of what the project will be used for.
          ui:options:
            rows: 2
        serviceOwners:
          title: Service Owners
          type: string
          ui:widget: textarea
          ui:description: The `@gcp.hc-sc.gc.ca` email addresses of users who should own this service, separated by comma.
          ui:options:
            rows: 2
          ui:placeholder: jane.doe@gcp.hc-sc.gc.ca, john.doe@gcp.hc-sc.gc.ca, steve.smith@gcp.hc-sc.gc.ca
    - title: Billing Details
      required:
        - totalBudget
      properties:
        totalBudget:
          title: Total Budget Amount (CAD)
          type: number
          minimum: 0,
        notifyList:
          title: Notify List
          type: string
          ui:widget: textarea
          ui:description: The `@phac-aspc.gc.ca` email addresses of users who should be notified of budget alerts, separated by a comma.
          ui:options:
            rows: 8
          ui:placeholder: jane.doe@phac-aspc.gc.ca, john.doe@phac-aspc.gc.ca, steve.smith@phac-aspc.gc.ca
    - title: Pull Request
      backstage:featureFlag: template-developer
      properties:
        closePullRequest:
          title: Close Pull Request?
          type: boolean
          default: true
          ui:widget: radio
          ui:description: Add the `[Test] ` prefix to close the pull request.

  steps:
    - id: ctx
      name: Get Context
      action: data-science-portal:template:get-context
      input:
        parameters: ${{parameters}}
        # TODO
        costCentre: ${{parameters.costCentre}}
        section32ManagerEmail: ${{parameters.section32ManagerEmail}}
        justification: ${{parameters.justification}}
        serviceOwners: ${{parameters.serviceOwners}}

    - id: prepare-pull-request
      name: Prepare Pull Request
      action: fetch:template
      input:
        url: ./${{steps.ctx.output.template}}/changes
        values: ${{steps.ctx.output.template_values}}

    - id: publish
      name: Submit Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{steps.ctx.output.repo_owner}}&repo=${{steps.ctx.output.repo_name}}
        branchName: ${{steps.ctx.output.branch}}
        title: ${{"[Test] " if parameters.closePullRequest else ''}}Create ${{steps.ctx.output.template}}
        description: ${{steps.ctx.output.pr_description}}
        targetPath: ./DMIA-PHAC/SciencePlatform/${{steps.ctx.output.template_values.folderName}}

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: 'View PR'
