---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-create
  title: Project Template
  description: Create a GCP Project with a budget and budget alerts. The Platform Team will review your request before the Project is created.
spec:
  owner: platform-team
  type: project
  parameters:
    - $yaml: ./template.parameters.project.yaml

    - title: Administration
      required:
        - costCentre
        - section32ManagerEmail
        - justification
      properties:
        costCentre:
          title: Cost Centre
          type: string
        costCentreName:
          title: Cost Centre Name
          description: The human-readable name for the Cost Centre.
          type: string
        section32ManagerEmail:
          title: Section 32 Manager Email Address
          type: string
          format: email
        justification:
          title: Justification
          ui:description: Provide a brief explanation of what the project will be used for.
          type: string
          ui:widget: textarea
          ui:options:
            rows: 2
        editorRefs:
          title: Editors
          ui:description: The users who should be able to edit this service.
          type: array
          items:
            type: string
          uniqueItems: true
          ui:field: MultiEntityPicker
          ui:options:
            catalogFilter:
              kind: User
        viewerRefs:
          title: Viewers
          ui:description: The users who should be able to view this service.
          type: array
          items:
            type: string
          uniqueItems: true
          ui:field: MultiEntityPicker
          ui:options:
            catalogFilter:
              kind: User

    - title: Billing
      required:
        - budgetAmount
      properties:
        budgetAmount:
          title: Annual Budget Amount (CAD)
          type: number
          default: 2000
        budgetAlertEmailRecipients:
          title: Budget Alert Email Recipients
          ui:description: The `@phac-aspc.gc.ca` email addresses of users who should be notified of budget alerts, separated by a comma.
          type: string
          ui:widget: textarea
          ui:options:
            rows: 2
          ui:placeholder: jane.doe@phac-aspc.gc.ca, john.doe@phac-aspc.gc.ca, steve.smith@phac-aspc.gc.ca
    - title: Pull Request
      backstage:permissions:
        tags:
          - template-developer
      properties:
        pullRequestAction:
          title: Pull Request Action
          type: string
          default: Diff Only
          enum:
            - Diff Only
            - Publish and Close Pull Request
            - Publish Pull Request

  steps:
    $yaml: ./template.steps.yaml

  output:
    links:
      - url: ${{steps['publish-pull-request'].output.remoteUrl}}
        title: 'View Pull Request'
