---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-create
  title: Project Template
  description: Create a GCP Project with a budget and budget alerts. The Platform Team will review your request before the Project is created.
spec:
  owner: platform-team
  type: project
  parameters:
    - $yaml: ./template.parameters.project.yaml
    - $yaml: ./template.parameters.administration.yaml
    - $yaml: ./template.parameters.billing.yaml
    - $yaml: ./template.parameters.pr.yaml

  steps:
    $yaml: ./template.steps.yaml

  output:
    links:
      - url: ${{steps['publish-pull-request'].output.remoteUrl}}
        title: 'View Pull Request'
