---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: backstage
  name: calculate-percent-budget-daily
spec:
  # Calculate the percentage budget used at the start of the workday in the East (6 AM, Atlantic).
  timeZone: Canada/Atlantic
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:8.8.0
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
              - |
                # We need to wait for the istio-proxy container to be healthy to make network requests.
                while ! curl -s -f http://127.0.0.1:15020/healthz/ready; do sleep 1; done

                # We need to configure the istio-proxy container to stop when the job is done.
                # A better solution is becoming available. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/.
                trap "curl --max-time 2 -s -f -XPOST http://127.0.0.1:15020/quitquitquit" EXIT

                curl -v --request POST -H "Authorization: Bearer $(BACKSTAGE_BUDGET_ALERT_EVENTS_TOKEN)" "$(BASE_URL)/api/budget-usage/sync"
              env:
                - name: BASE_URL
                  value: http://backstage.backstage.svc.cluster.local:7007
              envFrom:
                - secretRef:
                    name: backstage-auth-keys
          restartPolicy: Never
