---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xprojects.data-science-portal.phac-aspc.gc.ca
spec:
  defaultCompositionRef:
    name: project
  group: data-science-portal.phac-aspc.gc.ca
  names:
    kind: xProject
    plural: xprojects
  claimNames:
    kind: ProjectClaim
    plural: projectclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rootFolderId:
                  type: string
                projectName:
                  type: string
                projectId:
                  type: string
                projectEditors:
                  type: array
                  items:
                    type: string
                projectViewers:
                  type: array
                  items:
                    type: string
                labels:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  properties:
                    cost-centre:
                      type: string
                    # Additional user-defined labels are allowed. See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning.
                  required:
                    - cost-centre
              required:
                - rootFolderId
                - projectName
                - projectId
                - projectEditors
                - projectViewers
                - labels
