---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: ProjectClaim
metadata:
  name: phx-test-f163615c-20a9-463c-bc71-a8312a8b51b9
spec:
  rootFolderId: '108494461414'
  folderName: ph-test
  projectName: phx-test
  # projectId: 
