
---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: User
metadata:
  name: 
spec:
  profile:
    email: 


---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: User
metadata:
  name: 
spec:
  profile:
    email: 


---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: User
metadata:
  name: 
spec:
  profile:
    email: 


