---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: phx-01hz58ms9gy
  title: phx-ffdff
  annotations:
    backstage.io/source-location: https://github.com/PHACDevHub/sci-portal/DMIA-PHAC/SciencePlatform/phx-01hz58ms9gy/
    backstage.io/source-template: template:default/rad-lab-gen-ai-create
    cloud.google.com/project: phx-01hz58ms9gy
    data-science-portal.phac-aspc.gc.ca/budget-alert-recipients: rajan.subedi@focisolutions.com
spec:
  type: rad-lab-module
  owner: user:focisolutions.com/rajan.subedi
  lifecycle: experimental