---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.projectName}}
  title: ${{values.projectName}}
  description: A GCP Project with a budget and budget alerts.
spec:
  owner: group:${{values.projectName}} Owners
