---
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-dmia-phac
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    branch: main
    dir: DMIA-PHAC
    auth: ssh
    secretRef:
      name: git-creds
    period: 30s
