---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: ProjectClaim
metadata:
  name: phx-sean-demo-02-686bfc89-f49a-449c-b2b3-8e58a4a16747
spec:
  rootFolderId: '108494461414'
  projectName: phx-sean-demo-02
  projectId: phx-01hz1415ccw
  projectEditors:
    - user:sean.poulter@focisolutions.com
    - user:kendra.dezenosky@focisolutions.com
    - user:rajan.subedi@focisolutions.com
  projectViewers:
    - user:sean.poulter@focisolutions.com
  labels:
    cost-centre: 'abc123456789'
    vanity-name: 'phx-sean-demo-02'
