---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: ProjectClaim
metadata:
  name: php-sean-dev1-e330e675-48dd-4ae6-ab9e-ee8edee30b2b
spec:
  rootFolderId: '108494461414'
  folderName: ph-sean-dev1
  projectName: php-sean-dev1
  projectId: php-sean-dev1
