---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: phx-01hz2x4yszk
  title: phx-Vanity Name Test
  annotations:
    backstage.io/source-location: https://github.com/PHACDevHub/sci-portal/DMIA-PHAC/SciencePlatform/phx-01hz2x4yszk/
    backstage.io/source-template: template:default/rad-lab-data-science-create
    cloud.google.com/project: phx-01hz2x4yszk
spec:
  type: website
  owner: user:default/kendra.dezenosky
  lifecycle: experimental