---
apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: ProjectClaim
metadata:
  name: phx-Vanity Name Test-9adfda86-677e-4dda-8616-c8558d8b6d2f
spec:
  rootFolderId: '108494461414'
  folderName: ph-Vanity Name Test
  projectName: phx-Vanity Name Test
  # projectId: 
