
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: {{ owner }}
spec:
  profile:
    email: {{ owner }}


---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: {{ owner }}
spec:
  profile:
    email: {{ owner }}


---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: {{ owner }}
spec:
  profile:
    email: {{ owner }}


