apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: gen-ai-v3
spec:
  # Isolate the Terraform state for each GCP Project in a separate state file. The backend is configured in the ProviderConfig.
  providerConfigRef:
    name: t-project # "TO BE PATCHED" (with project ID)
  forProvider:
    module: git::https://github.com/GoogleCloudPlatform/rad-lab.git//modules/gen_ai?ref=v13.3.1
    source: Remote
    vars:
      ##
      # Project
      ##
      - key: billing_account_id
        value: "016B6D-6AB281-505940" # "TO BE PATCHED"
      - key: create_project
        value: "false"
      - key: folder_id
        value: "108494461414" # "TO BE PATCHED"
      - key: project_id_prefix # (Project ID)
        value: "t-project-004" # "TO BE PATCHED"
      - key: zone
        value: "northamerica-northeast1-a"

      ##
      # Security Controls
      ##
      - key: set_domain_restricted_sharing_policy
        value: "false"
      - key: set_external_ip_policy # TODO: Test access to the notebook. False is the default value. It might imply that we can't access it from a public IP.
        value: "false"
      - key: set_shielded_vm_policy
        value: "false" # TODO: Document this will change based on data classification.

      ##
      # Permissions
      ##
      - key: owner_users # "TO BE PATCHED"
        value: |
          ["rajan.subedi@gcp.hc-sc.gc.ca"]
      - key: trusted_users # "TO BE PATCHED"
        value: |
          ["rajan.subedi@gcp.hc-sc.gc.ca"]

      ##
      # (Option) Deep Learning VM Image
      #
      # See https://cloud.google.com/deep-learning-vm/docs/images.
      # This may affect the machine type and GPU acceleration.
      ##
      # - key: image_family
      #   value: ""

      ##
      # (Option) Machine Type
      ##
      - key: machine_type
        value: n1-standard-8

      ##
      # (Option) GPU Acceleration
      ##
      - key: enable_gpu_driver
        value: "false"
      # - key: gpu_accelerator_type
      #   value: "false"
      # - key: gpu_accelerator_core_count
      #   value: "false"

      - key: create_usermanaged_notebook
        value: "false"
# For data_science, the only new variable is set_trustedimage_project_policy. Try it with "true"
      # - key: set_trustedimage_project_policy
      #   value: "true"
