---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rad-lab-data-science-create
  title: RAD Lab Data Science Template
  description: Create a Vertex AI Workbench which hosts sample Jupyter Notebooks as part of data science module deployment. This Project has a budget and budget alerts. The Platform Team will review your request before the Project is created.
  tags:
    - rad-lab
spec:
  owner: platform-team
  type: service
  parameters:
    - $yaml: ../project-create/template.parameters.project.yaml
    - $yaml: ../project-create/template.parameters.team.yaml
    - $yaml: ../project-create/template.parameters.administration.yaml
    - $yaml: ../project-create/template.parameters.budget.yaml

    - title: RAD Lab Data Science
      required:
        - machineSize
      properties:
        machineSize:
          title: Machine Size
          description: Configure the Virtual Machine instance size.
          type: string
          default: small
          enum:
            - small
            - medium
            - large
          enumNames:
            - Small
            - Medium
            - Large

    - $yaml: ../project-create/template.parameters.pr.yaml

  steps:
    $yaml: ../project-create/template.steps.yaml

  output:
    links:
      - url: ${{steps['publish-pull-request'].output.remoteUrl}}
        title: 'View Pull Request'
