---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.projectId}}
  title: ${{values.projectName}}
  annotations:
    backstage.io/source-location: https://github.com/PHACDevHub/sci-portal/${{values.sourceLocation}}
    backstage.io/source-template: template:default/rad-lab-data-science-create
    cloud.google.com/project: ${{values.projectId}}
spec:
  type: rad-lab-module
  owner: ${{values.catalogEntityOwner}}
  lifecycle: experimental