---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.113.0
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.113.0
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator
  namespace: configconnector-operator-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.113.0
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator-service
  namespace: configconnector-operator-system
spec:
  ports:
    - name: controller-manager
      port: 443
  selector:
    cnrm.cloud.google.com/component: configconnector-operator
    cnrm.cloud.google.com/operator-system: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.113.0
  labels:
    cnrm.cloud.google.com/component: configconnector-operator
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator
  namespace: configconnector-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cnrm.cloud.google.com/component: configconnector-operator
      cnrm.cloud.google.com/operator-system: "true"
  serviceName: configconnector-operator-service
  template:
    metadata:
      annotations:
        cnrm.cloud.google.com/operator-version: 1.113.0
      labels:
        cnrm.cloud.google.com/component: configconnector-operator
        cnrm.cloud.google.com/operator-system: "true"
    spec:
      containers:
        - args:
            - --local-repo=/configconnector-operator/autopilot-channels
          command:
            - /configconnector-operator/manager
          image: gcr.io/gke-release/cnrm/operator:2d9421c
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: configconnector-operator
      terminationGracePeriodSeconds: 10
