apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
kind: ProjectClaim
metadata:
  name: php-sean-dev1-85eae68f-dda3-4eeb-aa4f-b1923332aef8
spec:
  rootFolderId: 108494461414
  folderName: ph-sean-dev1
  projectName: php-sean-dev1
  projectId: 
