Security Changes: {
    Cloud IAM {
        shape: image
        icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FSecurity%2FCloud%20IAM.svg
    }

    Storage Bucket {
        shape: image
        icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FStorage%2FCloud%20Storage.svg
    }
    Cloud IAM -> Storage Bucket: Permission changes
}

Cloud Monitoring {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FManagement%20Tools%2FMonitoring.svg
}

Cloud Logging {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FManagement%20Tools%2FLogging.svg
}

Log-based metric {
    shape: image
    icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FMetrics.svg
}

Notification channel (Email) {
    shape: image
    icon: https://icons.terrastruct.com/azure%2FManagement%20and%20Governance%20Service%20Color%2FAlerts.svg
}

Security Changes -> Cloud Logging: Platform logs captured
Cloud Logging -> Log-based metric: Filter and count matches
Cloud Monitoring -> Log-based metric: Monitor Changes
Cloud Monitoring -> Notification channel (Email): Send alert




