---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rad-lab-data-science
  annotations:
    crossplane.io/composition-schema-aware-validation-mode: strict
spec:
  compositeTypeRef:
    apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
    kind: xRadLabDataScience
  resources:
    - name: BASE-PROJECT
      base:
        apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
        kind: xProject
        spec:
          rootFolderId: "TO BE PATCHED"
          projectName: "TO BE PATCHED"
          projectId: "TO BE PATCHED"
          budget: "TO BE PATCHED"
          labels: "TO BE PATCHED"
          projectEditors: ["TO BE PATCHED"]
          projectViewers: ["TO BE PATCHED"]

      patches:
        - fromFieldPath: "spec.projectName"
          toFieldPath: "spec.projectName"
        - fromFieldPath: "spec.rootFolderId"
          toFieldPath: "spec.rootFolderId"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.projectId"
        - fromFieldPath: "spec.budget"
          toFieldPath: "spec.budget"
        - fromFieldPath: "spec.labels"
          toFieldPath: "spec.labels"
        - fromFieldPath: "spec.projectEditors"
          toFieldPath: "spec.projectEditors"
        - fromFieldPath: "spec.projectViewers"
          toFieldPath: "spec.projectViewers"

    - name: TERRAFORM-CONFIG
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: "TO BE PATCHED"
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: tf.upbound.io/v1beta1
              kind: ProviderConfig
              metadata:
                namespace: default
                name: "TO BE PATCHED"
              spec:
                configuration: "TO BE PATCHED"
          references:
            - dependsOn:
                apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
                kind: Project
                namespace: default
                name: "TO BE PATCHED"
      patches:
        - fromFieldPath: "spec.projectName"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-terraform-config"
        - fromFieldPath: "spec.projectName"
          toFieldPath: "spec.references[0].dependsOn.name"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.forProvider.manifest.spec.configuration"
          transforms:
            - type: string
              string:
                type: Format
                fmt: |
                  terraform {
                    backend "gcs" {
                      bucket  = "433b88e1164c5268-bucket-tfstate"
                      prefix  = "project-id/%s"
                    }
                  }

      readinessChecks:
        - type: NonEmpty
          fieldPath: status.atProvider.manifest

    - name: WORKSPACE
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: "TO BE PATCHED"
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: tf.upbound.io/v1beta1
              kind: Workspace
              metadata:
                namespace: default
                name: "TO BE PATCHED"
              spec:
                providerConfigRef:
                  name: "TO BE PATCHED"
                forProvider:
                  source: Remote
                  module: git::https://github.com/PHACDataHub/sci-portal.git//templates/rad-lab/data-science?ref=main
                  varmap:
                    # Project:
                    billing_account_id: "TO BE PATCHED"
                    folder_id: "TO BE PATCHED"
                    zone: "northamerica-northeast1-a"
                    create_project: "false"
                    project_id_prefix: "TO BE PATCHED"

                    # Security Controls:
                    set_domain_restricted_sharing_policy: "false"
                    set_external_ip_policy: "false"

                    # Notebook:
                    create_usermanaged_notebook: "false"
                    trusted_users: []

                    # (Option) Machine Type
                    machine_type: "TO BE PATCHED"

                    # (Option) Deep Learning VM Image
                    #
                    # See https://cloud.google.com/deep-learning-vm/docs/images.
                    # This may affect the machine type and GPU acceleration.
                    # image_family: ""

                    # (Option) GPU Acceleration
                    enable_gpu_driver: "false"
                    # gpu_accelerator_type: "false"
                    # gpu_accelerator_core_count: "false"

          references:
            - dependsOn:
                apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
                kind: Project
                namespace: default
                name: "TO BE PATCHED"
            - dependsOn:  # Custom ProviderConfig for storing terraform state
                apiVersion: tf.upbound.io/v1beta1
                kind: ProviderConfig
                namespace: default
                name: "TO BE PATCHED"
            - patchesFrom:
                apiVersion: v1
                kind: ConfigMap
                namespace: backstage
                name: backstage-config
                fieldPath: data.GCP_BILLING_ACCOUNT_ID
              toFieldPath: "spec.forProvider.varmap.billing_account_id"

      patches:
        - fromFieldPath: "spec.projectName"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-workspace"
        - fromFieldPath: "spec.projectName"
          toFieldPath: "spec.references[0].dependsOn.name"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.references[1].dependsOn.name"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.forProvider.manifest.spec.providerConfigRef.name"
        - fromFieldPath: "spec.rootFolderId"
          toFieldPath: "spec.forProvider.manifest.spec.forProvider.varmap.folder_id"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.forProvider.manifest.spec.forProvider.varmap.project_id_prefix"
        - fromFieldPath: "spec.notebookEditors"
          toFieldPath: "spec.forProvider.manifest.spec.forProvider.varmap.trusted_users"
        - fromFieldPath: "spec.machineSize"
          toFieldPath: "spec.forProvider.manifest.spec.forProvider.varmap.machine_type"
          transforms:
            - type: map
              map:
                "small": "n1-standard-2"
                "medium": "n1-standard-16"
                "large": "n1-standard-64"

    - name: PROVIDER-CONFIG-USES-PROJECT
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          replayDeletion: true
          of:
            apiVersion: data-science-portal.phac-aspc.gc.ca/v1alpha1
            kind: xProject
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: tf.upbound.io/v1beta1
            kind: ProviderConfig
            resourceRef:
              name: "TO BE PATCHED"
      patches:
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.by.resourceRef.name"

    - name: WORKSPACE-USES-PROVIDER-CONFIG
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          replayDeletion: true
          of:
            apiVersion: tf.upbound.io/v1beta1
            kind: ProviderConfig
            resourceRef:
              name: "TO BE PATCHED"
          by:
            apiVersion: tf.upbound.io/v1beta1
            kind: Workspace
            resourceRef:
              name: "TO BE PATCHED"
      patches:
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.of.resourceRef.name"
        - fromFieldPath: "spec.projectId"
          toFieldPath: "spec.by.resourceRef.name"
