---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xradlabdatasciences.data-science-portal.phac-aspc.gc.ca
spec:
  defaultCompositionRef:
    name: rad-lab-data-science
  group: data-science-portal.phac-aspc.gc.ca
  names:
    kind: xRadLabDataScience
    plural: xradlabdatasciences
  claimNames:
    kind: RadLabDataScienceClaim
    plural: radlabdatascienceclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Base Properties
                rootFolderId:
                  type: string
                projectName:
                  type: string
                projectId:
                  type: string
                projectEditors:
                  type: array
                  items:
                    type: string
                projectViewers:
                  type: array
                  items:
                    type: string
                labels:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  properties:
                    classification:
                      type: string
                    controlled-by:
                      type: string
                    cost-centre:
                      type: string
                    cost-centre-name:
                      type: string
                    pricing-structure:
                      type: string
                    vanity-name:
                      type: string
                    # Additional user-defined labels are allowed. See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning.
                  required:
                    - classification
                    - controlled-by
                    - cost-centre
                    - cost-centre-name
                    - pricing-structure
                    - vanity-name
              required:
                # Base Properties
                - rootFolderId
                - projectName
                - projectId
                - projectEditors
                - projectViewers
                - labels
