---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rad-lab-gen-ai-create
  title: RAD Lab GenAI Template
  description: Create a Vertex AI Workbench which hosts the contents of the public Google Cloud [Generative AI](https://github.com/GoogleCloudPlatform/generative-ai) repository. The repository contains notebooks and content that demonstrate how to use, develop, and manage generative AI workflows using generative AI, powered by Vertex AI and Generative AI App Builder on Google Cloud. This Project has a budget and budget alerts. The Platform Team will review your request before the Project is created.
  tags:
    - rad-lab
spec:
  owner: platform-team
  type: service
  parameters:
    - $yaml: ../project-create/template.parameters.project.yaml
    - $yaml: ../project-create/template.parameters.administration.yaml
    - $yaml: ../project-create/template.parameters.billing.yaml

    - title: RAD Lab GenAI
      required:
        - machineSize
      properties:
        machineSize:
          title: Machine Size
          description: Configure the Virtual Machine instance size.
          type: string
          default: small
          enum:
            - small
            - medium
            - large
          enumNames:
            - Small
            - Medium
            - Large

    - $yaml: ../project-create/template.parameters.pr.yaml

  steps:
    $yaml: ../project-create/template.steps.yaml

  output:
    links:
      - url: ${{steps['publish-pull-request'].output.remoteUrl}}
        title: 'View Pull Request'
