---
# This workflow is used for Continuous Integration for the root-sync/ directory.

name: CI for root-sync/

on:
  pull_request:
    branches:
      - main
    paths:
      - "root-sync/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./root-sync

    steps:
      - uses: actions/checkout@v4

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 472.0.0'

      - name: Install nomos
        run: gcloud components install nomos

      - name: Check manifests
        run: nomos vet --clusters "" --no-api-server-check --source-format unstructured
        # Refer to the docs https://cloud.google.com/anthos-config-management/docs/how-to/nomos-command#vet
