---
name: Close Test PR
on: pull_request

permissions:
  pull-requests: write

jobs:
  close-prs:
    name: Close Test PR
    if: ${{ startsWith( github.event.pull_request.title, '[Test] ') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}
      - name: Close PR
        run: |
          pwd
          gh pr close --delete-branch "$PR_URL"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
